# COURSE: A deep understanding of deep learning
## SECTION: Math prerequisites
### LECTURE: Matrix multiplication
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/dudl/?couponCode=202207

In [1]:
# import libraries
import numpy as np
import torch

# Using numpy

In [3]:
# create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some multiplications...
print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@C   ,2)), print(' ')
# print(np.round( B@C   ,2)), print(' ')
print(np.round( C.T@A ,2))

[[-0.07  1.53  1.55 -0.9   2.57]
 [ 0.37 -0.02 -1.8   1.59 -0.54]
 [-0.47  1.31 -1.89  0.84  0.76]]
 
[[-0.59 -0.75 -0.75 -1.38]
 [-1.14 -0.62  0.25 -0.15]
 [-0.57  0.15  0.32  0.06]
 [-1.8  -0.44 -1.51 -3.65]
 [-2.13 -1.19 -0.95 -2.64]
 [-0.02 -0.23 -1.18 -1.92]
 [-1.7  -2.05 -0.84 -1.78]]


# Using pytorch

In [5]:
# create some random matrices
A  = torch.randn(3,4)
B  = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1,dtype=torch.float )

# try some multiplications...
# print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@B.T ,2)), print(' ')
print(np.round( A@C1  ,2)), print(' ')
print(np.round( A@C2  ,2))

tensor([[ 1.6600, -0.2800,  0.8700,  0.1300,  1.0300, -1.6300, -0.1100],
        [ 1.5200,  0.2300,  1.1300,  0.9000,  1.6900, -1.7800, -1.5100],
        [ 0.0600,  0.6700,  3.1500,  0.3900,  4.8700, -0.7900, -5.6100]],
       dtype=torch.float64)
 
tensor([[ 1.6600, -0.2800,  0.8700,  0.1300,  1.0300, -1.6300, -0.1100],
        [ 1.5200,  0.2300,  1.1300,  0.9000,  1.6900, -1.7800, -1.5100],
        [ 0.0600,  0.6700,  3.1500,  0.3900,  4.8700, -0.7900, -5.6100]])
